/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 12
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_metadata = 1,
  sym_question_row = 2,
  sym_extensible_row = 3,
  sym_heading_row = 4,
  sym_info_row = 5,
  sym_control = 6,
  sym_node_id = 7,
  sym_comment = 8,
  sym_other = 9,
  sym_source_file = 10,
  aux_sym_source_file_repeat1 = 11,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_metadata] = "metadata",
  [sym_question_row] = "question_row",
  [sym_extensible_row] = "extensible_row",
  [sym_heading_row] = "heading_row",
  [sym_info_row] = "info_row",
  [sym_control] = "control",
  [sym_node_id] = "node_id",
  [sym_comment] = "comment",
  [sym_other] = "other",
  [sym_source_file] = "source_file",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_metadata] = sym_metadata,
  [sym_question_row] = sym_question_row,
  [sym_extensible_row] = sym_extensible_row,
  [sym_heading_row] = sym_heading_row,
  [sym_info_row] = sym_info_row,
  [sym_control] = sym_control,
  [sym_node_id] = sym_node_id,
  [sym_comment] = sym_comment,
  [sym_other] = sym_other,
  [sym_source_file] = sym_source_file,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_question_row] = {
    .visible = true,
    .named = true,
  },
  [sym_extensible_row] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_row] = {
    .visible = true,
    .named = true,
  },
  [sym_info_row] = {
    .visible = true,
    .named = true,
  },
  [sym_control] = {
    .visible = true,
    .named = true,
  },
  [sym_node_id] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_other] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '(') ADVANCE(44);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == '<') ADVANCE(51);
      if (lookahead == '[') ADVANCE(45);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(67);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '_') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'd') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'h') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '}') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(4);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '_') ADVANCE(20);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'c') ADVANCE(14);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(23);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'd') ADVANCE(21);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'h') ADVANCE(15);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(16);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == ')') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == '>') ADVANCE(39);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 28:
      if (lookahead == ']') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_metadata);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_question_row);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_question_row);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/' &&
          lookahead != '{') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_extensible_row);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '?') ADVANCE(31);
      if (lookahead == '\n' ||
          lookahead == '{') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_extensible_row);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_extensible_row);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_extensible_row);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/' &&
          lookahead != '{') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_heading_row);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_heading_row);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/' &&
          lookahead != '{') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_control);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_control);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_node_id);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == 'X') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == '>') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{') ADVANCE(27);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'b') ADVANCE(58);
      if (lookahead == 'd') ADVANCE(50);
      if (lookahead == 'n') ADVANCE(65);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'b') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'e') ADVANCE(66);
      if (lookahead == 'i') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'e') ADVANCE(66);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'e') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'g') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'm') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'm') ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'r') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 't') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 't') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 't') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_other);
      if (lookahead == 'x') ADVANCE(63);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_other);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(67);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_metadata] = ACTIONS(1),
    [sym_question_row] = ACTIONS(1),
    [sym_extensible_row] = ACTIONS(1),
    [sym_heading_row] = ACTIONS(1),
    [sym_info_row] = ACTIONS(1),
    [sym_control] = ACTIONS(1),
    [sym_node_id] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_other] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_metadata] = ACTIONS(5),
    [sym_question_row] = ACTIONS(7),
    [sym_extensible_row] = ACTIONS(7),
    [sym_heading_row] = ACTIONS(7),
    [sym_info_row] = ACTIONS(7),
    [sym_control] = ACTIONS(7),
    [sym_node_id] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [sym_other] = ACTIONS(7),
  },
  [STATE(2)] = {
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_metadata] = ACTIONS(11),
    [sym_question_row] = ACTIONS(13),
    [sym_extensible_row] = ACTIONS(13),
    [sym_heading_row] = ACTIONS(13),
    [sym_info_row] = ACTIONS(13),
    [sym_control] = ACTIONS(13),
    [sym_node_id] = ACTIONS(11),
    [sym_comment] = ACTIONS(11),
    [sym_other] = ACTIONS(13),
  },
  [STATE(3)] = {
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_metadata] = ACTIONS(17),
    [sym_question_row] = ACTIONS(20),
    [sym_extensible_row] = ACTIONS(20),
    [sym_heading_row] = ACTIONS(20),
    [sym_info_row] = ACTIONS(20),
    [sym_control] = ACTIONS(20),
    [sym_node_id] = ACTIONS(17),
    [sym_comment] = ACTIONS(17),
    [sym_other] = ACTIONS(20),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [23] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_eform(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
